<template>
  <div>
    <h1
      class="text-3xl xl:text-5xl text-center xl:text-left uppercase font-bold py-4"
    >
      FLASH Company Report Download
    </h1>
    <div v-if="showErrorMessage" class="text-fs-red py-12 font-bold">
      {{ errorMessage }}
    </div>
    <div class="text-lg text-center xl:text-left">
      Download the <span class="font-bold">FLASH</span> report your company
      executive requested via the flash@sap.com email.<br /><br />
      <NuxtLink
        to=""
        @click.prevent="
          getReport();
          showDownload = !showDownload;
        "
        class="max-w-max text-black font-bold uppercase rounded-lg cursor-pointer drop-shadow-lg bg-fs-yellow hover:bg-fs-yellow-light text-sm xl:text-base py-3 px-3 my-3 xl:py-4 xl:px-4 xl:my-4"
        >Download Company Report</NuxtLink
      >
      <br /><br />
      <UtilsMobileAppDownload
        message="It is recommended that you use the PowerPoint app for optimal viewing. To get the app, click here:"
        appStoreURL="https://apps.apple.com/us/app/microsoft-powerpoint/id586449534"
        playStoreURL="https://play.google.com/store/apps/details?id=com.microsoft.office.powerpoint&hl=en_US&gl=US&pli=1"
      />
      <u
        >You must be signed in as flash@sap.com in order to pull any survey
        generated by customers.</u
      >
      Please contact the assesssment moderators via if you wish to get
      <NuxtLink
        :to="`mailto:flash@sap.com?subject=FLASH User Access for Downloading`"
        activeClass="text-fs-yellow"
        class="underline"
        target="_blank"
        >flash@sap.com</NuxtLink
      >
      credentials.<br />
      <div v-if="showDownload">
        <UiLoader icon="flash-icon-bg-white.png" type="download" />
      </div>
      <br />
      <br />
      If you are unable to download your report and there is no messaging to
      explain, please click the "Sign In to Download Report" link from the
      flash@sap.com email and try again or contact us at:
      <NuxtLink
        :to="`mailto:flash@sap.com?subject=FLASH Download Problem - Assesssment ID: ${route.query.surveyId}`"
        activeClass="text-fs-yellow"
        class="underline"
        target="_blank"
        >flash@sap.com</NuxtLink
      >.
    </div>
  </div>
</template>

<script setup>
import nuxtStorage from "nuxt-storage";

const route = useRoute();

const token = ref(nuxtStorage.localStorage.getData("token") || false);

if (token.value === false || !route.query.surveyId) {
  navigateTo(`/profile?redirect=${route.fullPath}`);
}

const showDownload = ref(false);
const showErrorMessage = ref(false);
const errorMessage =
  "The assesssment ID could not be found or has been deleted due to an opt-out. Please try again.";
const config = useRuntimeConfig();
const companyName = ref(route.query.companyName || "");

definePageMeta({
  layout: "default",
}),
  useHead({
    title: "Download Report - FLASH - Enterprise Maturity Assessment",
    meta: [
      {
        name: "description",
        content: "Download Report - FLASH - Enterprise Maturity Assessment",
      },
    ],
  });

function getReport() {
  getDownload()
    .then((result) => {
      if (result.success === false) {
        showErrorMessage.value = true;
        showDownload.value = false;
      } else {
        showDownload.value = false;
        const url = window.URL.createObjectURL(
          new Blob([result], {
            type: "application/vnd.openxmlformats-officedocument.presentationml.presentation",
          })
        );
        const link = document.createElement("a");

        const today = new Date();
        const yyyy = today.getFullYear();
        let mm = today.getMonth() + 1; // Months start at 0!
        let dd = today.getDate();

        if (dd < 10) dd = "0" + dd;
        if (mm < 10) mm = "0" + mm;

        const formattedToday = dd + "-" + mm + "-" + yyyy;
        const filename =
          "FLASH Enterprise Retail Report - " +
          companyName.value.replace(/[^a-zA-Z ]/g, "") +
          " - " +
          formattedToday +
          ".pptx";

        link.href = url;
        link.setAttribute("download", filename);
        document.body.appendChild(link);

        link.click();
        link.remove();
        window.URL.revokeObjectURL(url);
      }
    })
    .catch((error) => {
      console.error("Get report could not be sent", error);
    });
}

async function getDownload() {
  return await $fetch(
    config.public.VUE_APP_API_URL +
      "/" +
      config.public.VUE_APP_API_VLM_REPORT_ROUTE,
    {
      method: "GET",
      query: {
        "x-auth-token": nuxtStorage.localStorage.getData("token"),
        surveyId: route.query.surveyId,
      },
    }
  );
}
</script>
